[package]
name = "quran-shorts-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
metadata = "0.1.8"
tokio = { version = "1", features = ["full"] }
xml-rs = "0.8"
